#
# NOTE: Keybind, maybe default setting?
#  Page Up/Down       Ctrl+Shift + PgUp/PgDn
#  Line Up/Down       Ctrl+Shift + Up/Down
#  Split horizontal
#    Sprit            Ctrl+Shift + Enter
#    Close            Ctrl+Shift + w
#    Jump             Ctrl+Shift + [/]
#  Tab
#    New              Ctrl+Shift + t
#    Close            Ctrl+Shift + w
#    Jump             Ctrl+Shift + Tab
#
# NOTE: Available fonts
#  fc-list : family spacing outline scalable | grep -e spacing=100 -e spacing=90 | grep -e outline=True | grep -e scalable=True | sort
# NOTE: Reflection after update
#  kitty @ set-colors --all ~/.config/kitty/kitty.conf
#

font_size                     12

# NOTE: Install extra/ttf-cascadia-mono-nerd
font_family                   CaskaydiaMono NFM ExtraLight
bold_font                     auto
italic_font                   auto
bold_italic_font              auto

symbol_map                    U+3000-U+9FFF Noto Sans Mono CJK JP

# modify_font                 underline_position -2
# modify_font                 underline_thickness 150%
# modify_font                 strikethrough_position 2px
# modify_font                 cell_width 80%
# modify_font                 cell_height -2px
# modify_font                 baseline 3

cursor_shape                  underline
cursor_shape_unfocused        hollow
cursor_beam_thickness         1.5
cursor_underline_thickness    2.0
cursor_trail                  20
cursor_trail_decay            0.1 0.4
cursor_trail_start_threshold  2

confirm_os_window_close       0

window_margin_width           2
window_padding_width          2

include                       kitty_color.conf
