#
# This is a sample ini file.
# For actual use, rename it to `my_mount_nas.ini`.
# A `#` at the beginning of a line is treated as a comment.
# Ignore blank lines as well.
#
mount_device=(mount_device)
mount_point=(mount_point)
