#
# This is a sample ini file.
# For actual use, rename it to `my_wallpaper_set_one_color.ini`.
# A `#` at the beginning of a line is treated as a comment.
# Ignore blank lines as well.
#
default_color=#08052b
default_size=1920x1080
