#
# This is a sample ini file.
# For actual use, rename it to `my_wallpaper_set_two_gradation.ini`.
# A `#` at the beginning of a line is treated as a comment.
# Ignore blank lines as well.
#
default_color_1=#08052b
default_color_2=#ff7f7f
default_direction=NorthWest
default_size=1920x1080
